language: php
php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm
matrix:
    allow_failures:
        - php: hhvm # fails with close socket
before_script:
    - composer install --prefer-source --dev --no-interaction
script:
    - mkdir -p build/logs
    - phpunit --coverage-clover build/logs/clover.xml
after_script:
    - php vendor/bin/coveralls -v
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

